import Navbar from './component/Navbar';
import './globals.css'
export const metadata = {
  title: "Ahmed Mustafa",
  description: "Generated by Ahmed Mustafa",
  icons: {
    icon: "/image.png", 
   
  },
};

export default function RootLayout({ children }) {
  return (
 
      <html lang="en">
           
        <body className="antialiased font-serif">
          <div className="relative z-10">
       <Navbar/>
            {children}
          </div>
        </body>
      </html>

  );
}